import type { Screen } from "../state.js";
export interface KeybindingActions {
    onNavigate: (direction: "up" | "down" | "left" | "right") => void;
    onSelect: () => void;
    onNextPane: () => void;
    onPrevPane: () => void;
    onNextDetailTab: () => void;
    onPrevDetailTab: () => void;
    onSetLogMode: (mode: "structured" | "raw" | "errors") => void;
    onApprove: () => void;
    onContinue: () => void;
    onRetry: () => void;
    onKill: () => void;
    onDelete: () => void;
    onNewRun: () => void;
    onQuit: () => void;
    onEnterInput: () => void;
    onExitInput: () => void;
    onBack: () => void;
    onRework: () => void;
    onOpenExternal: () => void;
    onApprovalsView: () => void;
    onToggleDiff: () => void;
    onPause: () => void;
    onTakeOver: () => void;
    onToggleAutopilot: () => void;
    onRunnersView: () => void;
    onAutopilotView: () => void;
    onFilter: () => void;
    onCommandPalette: () => void;
    onHelp: () => void;
    onDetailTabShortcut: (index: number) => void;
    onGoTop: () => void;
    onGoBottom: () => void;
    onEscalate: () => void;
    onSettingsView: () => void;
    onRerunWithProfile: () => void;
    onJumpArtifact: () => void;
    onJumpGate: () => void;
    onJumpError: () => void;
}
export declare function useKeybindings(actions: KeybindingActions, screen: Screen, inputMode: boolean): void;
